### ISSUE TITLE
[API] Top and Popular endpoints return duplicate UIDs

### ISSUE THREAD

**Issue by Ed-zo** [LaBlazer/storrmbox#23] opened 2020-02-20 12:24 UTC
**Description**
Top and Popular endpoints return duplicate uids but only for series! It seems to be functioning well for the movies.

UIDs for **popular series** are three times repeated and for **top series** four times repeated.

**Expected behavior**
List of popular/top media UIDs should be unique.

**Screenshots**
Map of uid's count
![image](https://user-images.githubusercontent.com/15330300/74933131-a76f6b00-53e3-11ea-8856-c17236eacdc3.png)

**Comment by LaBlazer** [comment] 2020-02-20 14:08
I know about this issue, it's already in TODO at https://github.com/LaBlazer/storrmbox/projects/2. It's an issue with the caching system.

**Comment by LaBlazer** [comment] 2020-03-09 12:51
Cannot reproduce this currently, closing until it appears again...

**Closed by LaBlazer** 2020-03-09 12:51 UTC
Labels: backend, bug
